/*
 *
 * MyTrades constants
 *
 */

export const RETRIEVE_MY_TRADES = 'app/MyTRADES/RETRIEVE_MY_TRADES';
export const RETRIEVE_MY_TRADES_SUCCESS = 'app/MyTRADES/RETRIEVE_MY_TRADES_SUCCESS';
export const CHANGE_ACTIVE_NAV_KEY = 'app/MyTrades/CHANGE_ACTIVE_NAV_KEY';
export const INCREMENT_ACTIVE_NAV_KEY = 'app/MyTrades/INCREMENT_ACTIVE_NAV_KEY';
export const DECREMENT_ACTIVE_NAV_KEY = 'app/MyTrades/DECREMENT_ACTIVE_NAV_KEY';
export const CANCEL_REQUEST = 'app/MyTrades/CANCEL_REQUEST';
export const CANCEL_REQUEST_SUCCESS = 'app/MyTrades/CANCEL_REQUEST_SUCCESS';
export const APPROVE_REQUEST = 'app/MyTrades/APPROVE_REQUEST';
export const APPROVE_REQUEST_SUCCESS = 'app/MyTrades/APPROVE_REQUEST_SUCCESS';
export const DECLINE_REQUEST = 'app/MyTrades/DECLINE_REQUEST';
export const DECLINE_REQUEST_SUCCESS = 'app/MyTrades/DECLINE_REQUEST_SUCCESS';
export const SET_TO_RETURNED = 'app/MyTrades/SET_TO_RETURNED';
export const SET_TO_RETURNED_SUCCESS = 'app/MyTrades/SET_TO_RETURNED_SUCCESS';

