
export const RETRIEVE_AVAILABLE_BOOKS = 'app/HomePage/RETRIEVE_AVAILABLE_BOOKS';
export const RETRIEVE_AVAILABLE_BOOKS_SUCCESS = 'app/HomePage/RETRIEVE_AVAILABLE_BOOKS_SUCCESS';
export const REQUEST_TRADE = 'app/HomePage/REQUEST_TRADE';
export const REQUEST_TRADE_SUCCESS = 'app/HomePage/REQUEST_TRADE_SUCCESS';
